import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";

const inter = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Khana Khazana - Home",
    description: "Generated by create next app Khana Khazana",
};

export default async function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <AuthProvider>
                    <Navbar />
                    <main className=''>{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
